[project]
name = "bertopic-ticket-triage"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bertopic>=0.17.3",
    "hf-xet>=1.1.10",
    "ipykernel>=6.30.1",
    "kagglehub[hf-datasets]>=0.3.13",
]
